# Generated by Django 4.1.3 on 2022-11-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category1',
            new_name='Category',
        ),
    ]
